### ISSUE TITLE
No proper way of knowing whether authentication is successful

### ISSUE THREAD

**Issue by pakedge** [fiorix/txmongo#74]
When using txmongo, we use code like this:

    mongoConnection=yield txmongo.MongoConnection(MONGODB_HOST, MONGODB_PORT, pool_size=CONNECTION_POOL_SIZE)
    db=getattr(self.mongoConnection, DEFAULT_MONGO_DB_NAME)
    yield db.authenticate(MONGODB_USER, MONGODB_PASS)

It would be nice to know if authentication is successful. However, the database authenticate method does not return anything to let you know this. It only calls connection authenticate_with_nonce and that sets a variable db._authenticated to True when authenticated. But it is bad form for any external python script to check on the value of a member variable that starts with an underscore.

I suggest that you add a method like is_authenticated() to db that returns True or False. This way we know when the connection is ready for successful writing or other database interactions.

**Comment by pakedge** [comment]
There appears to be a bigger error here. Suppose I create a MongoConnection (which is really a ConnectionPool subclass) with 100 connections (pool_size=100). It looks like everything authenticates fine (_authenticated is True). But it then crashes sometimes in collection.py at line 318 in get_authenticated_protocol. Specifically, when another thread calls the an insert command, it gets to collection.insert, line 237 of insert:

        if self._database._authenticated :
            proto = yield self._database.connection.get_authenticated_protocol(self._database)
        else :
            proto = yield self._database.connection.getprotocol()
Since _authenticated is True, the call is made on line 237 to get_authenticatedProtocol. Here is what that looks like:

    @defer.inlineCallbacks
    def get_authenticated_protocol(self,database) :
        # Get the next protocol available for communication in the pool
        connection = self.__pool[self.__index]
        database_name = str(database)

        if database_name not in connection.auth_set :
            name  = self.cred_cache[database_name][0]
            password = self.cred_cache[database_name][1]
            yield self.authenticate_with_nonce(database,name,password)
        else :
            self.__index = (self.__index + 1) % self.__pool_size

        defer.returnValue(connection.instance)

It crashes with a KeyError on line 318:
name  = self.cred_cache[database_name][0]

This means that database_name is not in self.cred_cache!
Surprisingly enough, if we restart our process a few times, this issue goes away. But I really don't know why this error would pop up in the first place.

**Comment by pakedge** [comment]
Possible solution: in connection.py around line 291. Instead of adding database_name to the auth_set of current_connection, why not add it to ALL connections in the thread pool? Or are some previously opened connections then having their auth_sets emptied in clientConnectionLost?

Something's not right here when we have multiple connections in a connection pool.

**Comment by IlyaSkriblovsky** [comment]
Hi! Please check out latest changes to txmongo. I've reworked all authentication-related stuff and my pull request was merged yesterday. Old authentication code had race conditions and was unstable with connection pool with pool_size > 1. Please test latest master branch in your scenarios.

Returning status of authentication is not that easy. MongoConnection is actually a connection pool and each individual connection in the pool might be active or inactive at any moment of time. What should `authenticate()` return if all connections in the pool is not active (like just after creating MongoConnection instance in your example)? In this case `authenticate()` just remembers that it needs to authenticate with specified credentials when any connection is going online.

My new implementation of `authenticate()` behaves this way:

1. If *any* connection in the pool is active when you call it, it will wait until *all* active connections will be authenticated (as long as you call it with `yield` of course)
2. If there is no active connections in the pool, it will return immediately

But your original example is the case 2, so it won't help you in this scenario.

I suggest you to issue some useless `find_one()` right after `authenticate()` and catch exception about failed authentication.

**Comment by fiorix** [comment]
Sounds like @pakedge needs a git pull.
Thanks @IlyaSkriblovsky.
